name: Heroku Awake

on:
  schedule:
    - cron: "*/10 3-20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: ${{ secrets.WEB_ADDRESS }}
