name: Update

on:
  push:
  schedule:
  - cron: '20 2 * * *'
    
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      uses: TG908/fork-sync@v1.5
      with:
        token: ${{ secrets.FS_PAT }}
        owner: smogon
        base: master
        head: master
  copy:
    name: Copy
    needs: sync
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.GH_PAT }}
        src_path: /.
        dst_owner: codeinteger6
        dst_repo_name: showdown-server
        src_branch: master
        dst_branch: master
